### ISSUE TITLE
Update deep-extend after vulnerability is fixed

### ISSUE THREAD

**Issue by lc3t35** [dominictarr/rc#110]
deep-extend is vulnerable to prototype pollution attacks (https://github.com/unclechu/node-deep-extend/issues/39). The vulnerability exists in the utility function where the prototype of `Object` can be overwritten to add or modify existing property on all objects.
Please update as soon as deep-extend is updated

**Comment by schorfES** [comment]
Hello, I've seen the [vulnerability](https://github.com/unclechu/node-deep-extend/issues/39) has been fixed in release [v0.5.1](https://github.com/unclechu/node-deep-extend/releases/tag/v0.5.1).

**Comment by dominictarr** [comment]
fixed in rc@1.2.7
