### ISSUE TITLE
Please tag 1.2.8 on Github

### ISSUE THREAD

**Issue by mohe2015** [dominictarr/rc#130]
That version is on npm but not here.

Would be great if you could fix it.

**Comment by magano** [comment]
Don't install this version!
It has malicious code!

Something similar to what happened with coa
https://github.com/veged/coa/issues/99

I installed it locally and it came with two files which were not there before and are not to be expected
- compile.js
- compile.bat

**Comment by mohe2015** [comment]
`npm pack rc@1.2.8` didn't show me these files @magano

**Comment by magano** [comment]
I'm sorry, it was not this version but 1.2.9.
I think it was already pulled from the registry.

**Comment by mohe2015** [comment]
Is it possible to somehow show the deleted versions somewhere?

**Comment by mohe2015** [comment]
https://github.com/advisories/GHSA-g2q5-5433-rhrf

**Comment by magano** [comment]
Great! I wasn't aware of this link
