### ISSUE TITLE
Can there be a way to allow only json or ini but not both?

### ISSUE THREAD

**Issue by ljharb** [dominictarr/rc#38]
I'd like my project's config files to be in a consistent format. Can I pass an option to either disable `json` or `ini` parsing?

**Comment by megastef** [comment]
Hi, I just started to use the .ini format and it was one reason to use "rc" beside the perfect file locations/environment scan not conflicting with others (not like 'node-config', which can't be used in a module) - About .ini format:  I think its easier to read & write for Sysadmins e.g. in /etc/ a .json file looks a bit strange and missing a comma or quote could destroy the file format ...

**Comment by dominictarr** [comment]
@megastef thanks, good point. It can be easy to fall into the trap of thinking that everyone is a javascript programmer, but that is not true.

**Comment by loopmode** [comment]
Very old and closed discussion, but my two cents nonetheless :)

I totally like the ini format. It's just much more terse and consise. especially using the dot-notation in section names.

In my use cases, I typically have a rather complex and deeply nested default configuration. Typically, during development, you don't need to change/override anything.

However, in production, things need to be changed, especially now in times of docker and virtualization.
So, typically, just a couple of values need to be overridden, mostly they are deeply nested, and the change is often done by admins or other non-coders.

In this scenario, the ini format wins bigtime.
Overriding a single value means max two lines in ini format - no matter how deeply the value is nested.
In JSON format on the other hand, it depends on the level of nesting - the deeper the value is nested, the more noise you create with brackets and quotes and possibly new lines.

```
[orientdb.server.use]
    port = 4000
```

vs 

```
{
    "orientdb": {
        "server": {
            "use": {
                "port": 4000
            }
        }
    }
}
```
