### ISSUE TITLE
minimist supports option aliases, can rc?

### ISSUE THREAD

**Issue by ljharb** [dominictarr/rc#39]
With `minimist`, I can do:
```js
minimist(process.argv, {
  boolean: ['a', 'b'],
  alias: { c: 'a' },
  default: defaults
});
```

Using `rc`, `minimist` figures out the booleans for me, and I provide the `defaults` explicitly - but there's no way to specify aliases.

**Comment by dominictarr** [comment]
yes. use the custom argv parser feature to pass in your own minimist instance: https://github.com/dominictarr/rc#advanced-usage

**Comment by ljharb** [comment]
That requires me to parse options with minimist and then use `rc`, which seems like it defeats the simplicity of just using this module. Could we not just add an `aliases` object param to `rc` somewhere?

**Comment by dominictarr** [comment]
We added that feature to allow you to use rc with other parsers, such as nopt.
having an `aliases` param would make it coupled to minimist.

if `rc` was gonna have an aliases option, then maybe it should work for all the config options?
sometimes, I apply some transform after all the config is parsed, say, to convert hyphenated options into camel case. you could apply aliases like that too.

**Comment by ljharb** [comment]
I like that idea - seems like it'd make `rc` more useful.
