### ISSUE TITLE
Update ini dependency - strict mode issues

### ISSUE THREAD

**Issue by anthonator** [dominictarr/rc#40]
When using rc in strict mode I'm getting octal literal errors.

```
/Users/anthonator/Documents/Projects/sticksnleaves/pet-records/api/node_modules/pwny/node_modules/rc/node_modules/ini/ini.js:49
                  .replace(/\2LITERAL\\1LITERAL\2/g, '\1')
```

This looks to be caused by your dependency on the [ini](https://github.com/isaacs/ini) package.

According to [this issue](https://github.com/isaacs/ini/issues/17) the problem has been acknowledged. Although the issue isn't closed [this PR](https://github.com/isaacs/ini/pull/21) indicates that it's been fixed. Looking through master I see the change as well.

**Comment by dominictarr** [comment]
fixed.
