### ISSUE TITLE
Version history?

### ISSUE THREAD

**Issue by ChiperSoft** [dominictarr/rc#50]
Came here to see what changed between 0.6.0 and 1.0 and was disappointed that there is neither a history.md file, nor are there any git version tags.  After looking through the commits it doesn't appear that there were any breaking changes, but I'd feel a lot more comfortable about upgrading if there was some kind of history prose.

**Comment by dominictarr** [comment]
okay I pushed the tags - look at closed pull requests. There was a breaking change, but it was very small.
