### ISSUE TITLE
Yaml support

### ISSUE THREAD

**Issue by Deadarius** [dominictarr/rc#52]
Is it planned? I am willing to make a pull request if it matches this module's vision.

**Comment by dominictarr** [comment]
If you want to use a custom format use this: https://github.com/dominictarr/rc#pass-in-your-own-parser

we will not be adding any more parsers to rc's core.

**Comment by dominictarr** [comment]
If you want to use a custom format use this: https://github.com/dominictarr/rc#pass-in-your-own-parser

we will not be adding any more parsers to rc's core.
