### ISSUE TITLE
Idea: read "root" option to stop reading in parent dir for other config

### ISSUE THREAD

**Issue by MoOx** [dominictarr/rc#63]
Some tools like eslint or editorconfig support this kind of option, would you be open to support that via a new argument (a third argument that can be a string ("root", "stop", whatever) or a bool (for "root": true)?

**Comment by dominictarr** [comment]
hmmm, this doesn't really vibe with my intuitions... if that is really a problem, it's probably that your setup is too complex. If you really think this is a good idea, can you provide a detailed description about what problem this would solve, and when you would use it.

**Comment by MoOx** [comment]
The idea is simple http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy (see root explanation). It's not overkill or complex. Just a simple option to stop looking up in the fs tree.

**Comment by dominictarr** [comment]
Wow, eslint has a whole inheritence system for configuration!
You didn't answer my question,
> If you really think this is a good idea, can you provide a detailed description about what problem this would solve, and when you would use it?

**Comment by MoOx** [comment]
Just stop accessing the fs when a user wants his configuration to be as defined in at a specific level without trying to get (+merge) all other configuration files in parent directory.
Like "hey, I know this config is engough, not need to lookup for other config to merge". But maybe I should just no use this module and create another one to load one file only.

**Comment by dominictarr** [comment]
@MoOx "because the user wants to" is not an answer, _why_ does the user want to? why is touching another file a problem? what is the user trying to do that can't be done with `rc` as it is?

**Comment by simonsmith** [comment]
I have a use case where I keep a global `.stylelintrc` in my home directory for use with syntastic in Vim. However when I open a project that has its own `.stylelintrc` I don't want that to merge with my personal preferences, nor do I want a build script to pick up my personal configs. Being able to add `root: true` in the project would prevent this being an issue.
