### ISSUE TITLE
Making rc more configurable

### ISSUE THREAD

**Issue by zkochan** [dominictarr/rc#92]
We use `rc` for [pnpm](https://github.com/pnpm/pnpm) but we need the configs look exactly as they do with npm. Would you consider making rc more configurable to allow us rewrite some of the things?

Currently we need the possibility to use `--userconfig` instead of `--config` as the parameter for the config file. Related issue at pnpm https://github.com/pnpm/pnpm/issues/40. Can this be made configurable?

Also rc currently uses the `${appname}_` prefix for env variables. It would be great to be able to specify this prefix as we need the `npm_config_` prefix instead.

**Comment by dominictarr** [comment]
Aha, well you should just use the config module that npm uses. https://www.npmjs.com/package/npm-config
then you'll catch all the weird edgecases that npm uses for legacy reasons, but most importantly you'll do exactly what npm does.

**Comment by zkochan** [comment]
yeah, maybe we'll do just that
